export const MEAL_CREATE_REQUEST = 'MEAL_CREATE_REQUEST';
export const MEAL_CREATE_SUCCESS = 'MEAL_CREATE_SUCCESS';
export const MEAL_CREATE_FAIL = 'MEAL_CREATE_FAIL';

export const MEAL_DELETE_REQUEST = 'MEAL_DELETE_REQUEST';
export const MEAL_DELETE_SUCCESS = 'MEAL_DELETE_SUCCESS';
export const MEAL_DELETE_FAIL = 'MEAL_DELETE_FAIL';

export const MEAL_UPDATE_REQUEST = 'MEAL_UPDATE_REQUEST';
export const MEAL_UPDATE_SUCCESS = 'MEAL_UPDATE_SUCCESS';
export const MEAL_UPDATE_FAIL = 'MEAL_UPDATE_FAIL';

export const MEAL_LIST_REQUEST = 'MEAL_LIST_REQUEST';
export const MEAL_LIST_SUCCESS = 'MEAL_LIST_SUCCESS';
export const MEAL_LIST_FAIL = 'MEAL_LIST_FAIL';

export const MEAL_LIST_SET = 'MEAL_LIST_SET';
