export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST';
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS';
export const RECIPE_CREATE_FAIL = 'RECIPE_CREATE_FAIL';

export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST';
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS';
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';
