export const WEEK_CREATE_REQUEST = 'WEEK_CREATE_REQUEST';
export const WEEK_CREATE_SUCCESS = 'WEEK_CREATE_SUCCESS';
export const WEEK_CREATE_FAIL = 'WEEK_CREATE_FAIL';

export const WEEK_LIST_REQUEST = 'WEEK_LIST_REQUEST';
export const WEEK_LIST_SUCCESS = 'WEEK_LIST_SUCCESS';
export const WEEK_LIST_FAIL = 'WEEK_LIST_FAIL';

export const WEEK_SET_SELECTED = 'WEEK_SET_SELECTED';
